apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: pods-list-default-role
    namespace: prop3d
  rules:
  - apiGroups:
    - "*"
    resources:
     - "*"
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
     - "pods/exec"
    verbs:
     - create
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
---
apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: pods-list-default-rolebinding
    namespace: prop3d
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: pods-list-default-role
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: user
  - kind: ServiceAccount
    name: default
    namespace: prop3d
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""