apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prop3d-hsds
  name: prop3d-hsds
  namespace: prop3d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prop3d-hsds
  template:
    metadata:
      labels:
        app: prop3d-hsds
    spec:
      containers:
        - name: head
          image: hdfgroup/hsds:sha-3e9c651
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "128M"
              cpu: "50m"
            limits:
              memory: "512M"
              cpu: "100m"
          volumeMounts:
            - name: config
              mountPath: "/config/config.yml"
              subPath: config.yml
            - name: override
              mountPath: "/config/override.yml"
              subPath: override.yml
          ports:
            - containerPort: 5100
          env:
            - name: NODE_TYPE
              value: head_node
            - name: HEAD_PORT
              value: "5100" 
            - name: TARGET_SN_COUNT
              value: "1"
            - name: TARGET_DN_COUNT
              value: "1"
        - name: sn
          image: hdfgroup/hsds:sha-3e9c651
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "2G"
              cpu: "500m"
            limits:
              memory: "4G"
              cpu: "1000m"
          volumeMounts:
            - name: config
              mountPath: "/config/config.yml"
              subPath: config.yml
            - name: override
              mountPath: "/config/override.yml"
              subPath: override.yml
          ports:
            - containerPort: 5101
          env:
            - name: NODE_TYPE
              value: sn
            - name: HEAD_PORT
              value: "5100" 
            - name: "AWS_ACCESS_KEY_ID"
              valueFrom:
                secretKeyRef:
                  name: arctic-minio-secrets
                  key: MINIO_ROOT_USER
            - name: "AWS_SECRET_ACCESS_KEY"
              valueFrom:
                secretKeyRef:
                  name: arctic-minio-secrets
                  key: MINIO_ROOT_PASSWORD
            - name: PASSWORD_SALT
              valueFrom:
                secretKeyRef:
                  name: prop3d-hsds-secrets
                  key: PASSWORD_SALT
          livenessProbe:
            httpGet:
              path: /info
              port: 5101
            initialDelaySeconds: 5
            periodSeconds: 60
        - name: dn1
          image: hdfgroup/hsds:sha-3e9c651
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["/sbin/killall5", "-15"]
          resources:
            requests:
              memory: "1G"
              cpu: "500m"
            limits:
              memory: "2G"
              cpu: "1000m"
          volumeMounts:
            - name: config
              mountPath: "/config/config.yml"
              subPath: config.yml
            - name: override
              mountPath: "/config/override.yml"
              subPath: override.yml
          ports:
            - containerPort: 6101
          env:
            - name: NODE_TYPE
              value: dn
            - name: HEAD_PORT
              value: "5100"
            - name: DN_PORT
              value: "6101"
            - name: "AWS_ACCESS_KEY_ID"
              valueFrom:
                secretKeyRef:
                  name: prop3d-arctic-minio-secrets
                  key: MINIO_ROOT_USER
            - name: "AWS_SECRET_ACCESS_KEY"
              valueFrom:
                secretKeyRef:
                  name: prop3d-arctic-minio-secrets
                  key: MINIO_ROOT_PASSWORD
          livenessProbe:
            httpGet:
              path: /info
              port: 6101
            initialDelaySeconds: 5
            periodSeconds: 60
        - name: dn2
          image: hdfgroup/hsds:sha-3e9c651
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["/sbin/killall5", "-15"]
          resources:
            requests:
              memory: "1G"
              cpu: "500m"
            limits:
              memory: "2G"
              cpu: "1000m"
          volumeMounts:
            - name: config
              mountPath: "/config/config.yml"
              subPath: config.yml
            - name: override
              mountPath: "/config/override.yml"
              subPath: override.yml
          ports:
            - containerPort: 6102
          env:
            - name: NODE_TYPE
              value: dn
            - name: HEAD_PORT
              value: "5100"
            - name: DN_PORT
              value: "6102" 
            - name: "AWS_ACCESS_KEY_ID"
              valueFrom:
                secretKeyRef:
                  name: prop3d-arctic-minio-secrets
                  key: MINIO_ROOT_USER
            - name: "AWS_SECRET_ACCESS_KEY"
              valueFrom:
                secretKeyRef:
                  name: prop3d-arctic-minio-secrets
                  key: MINIO_ROOT_PASSWORD
          livenessProbe:
            httpGet:
              path: /info
              port: 6102
            initialDelaySeconds: 5
            periodSeconds: 60
        - name: dn3
          image: hdfgroup/hsds:sha-3e9c651
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["/sbin/killall5", "-15"]
          resources:
            requests:
              memory: "1G"
              cpu: "500m"
            limits:
              memory: "2G"
              cpu: "1000m"
          volumeMounts:
            - name: config
              mountPath: "/config/config.yml"
              subPath: config.yml
            - name: override
              mountPath: "/config/override.yml"
              subPath: override.yml
          ports:
            - containerPort: 6103
          env:
            - name: NODE_TYPE
              value: dn
            - name: HEAD_PORT
              value: "5100" 
            - name: DN_PORT
              value: "6103"
            - name: "AWS_ACCESS_KEY_ID"
              valueFrom:
                secretKeyRef:
                  name: prop3d-arctic-minio-secrets
                  key: MINIO_ROOT_USER
            - name: "AWS_SECRET_ACCESS_KEY"
              valueFrom:
                secretKeyRef:
                  name: prop3d-arctic-minio-secrets
                  key: MINIO_ROOT_PASSWORD
          livenessProbe:
            httpGet:
              path: /info
              port: 6103
            initialDelaySeconds: 5
            periodSeconds: 60
        - name: dn4
          image: hdfgroup/hsds:sha-3e9c651
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["/sbin/killall5", "-15"]
          resources:
            requests:
              memory: "1G"
              cpu: "500m"
            limits:
              memory: "2G"
              cpu: "1000m"
          volumeMounts:
            - name: config
              mountPath: "/config/config.yml"
              subPath: config.yml
            - name: override
              mountPath: "/config/override.yml"
              subPath: override.yml
          ports:
            - containerPort: 6104
          env:
            - name: NODE_TYPE
              value: dn
            - name: HEAD_PORT
              value: "5100" 
            - name: DN_PORT
              value: "6104"
            - name: "AWS_ACCESS_KEY_ID"
              valueFrom:
                secretKeyRef:
                  name: prop3d-arctic-minio-secrets
                  key: MINIO_ROOT_USER
            - name: "AWS_SECRET_ACCESS_KEY"
              valueFrom:
                secretKeyRef:
                  name: prop3d-arctic-minio-secrets
                  key: MINIO_ROOT_PASSWORD
          livenessProbe:
            httpGet:
              path: /info
              port: 6104
            initialDelaySeconds: 5
            periodSeconds: 60    
      volumes:
        - name: config
          configMap:
            name: prop3d-hsds-config
        - name: override
          configMap:
            name: prop3d-hsds-override
