apiVersion: v1
kind: ConfigMap
metadata:
  name: prop3d-hsds-override
  namespace: prop3d
data:
  override.yml: >+
    log_level: DEBUG
    
    bucket_name: arctic-hsds
    
    server_name: Highly Scalable Data Service (HSDS) on RC Kubernetes for UVA Arctic 
    
    password_salt: 
    
    hsds_endpoint: http://prop3d-hsds.pods.uvarc.io
    
    aws_s3_gateway: http://prop3d-arctic-minio-service.prop3d.svc.cluster.local:9000

    chunk_mem_cache_expire: 0

    chunk_mem_cache_size: 512m 

    metadata_mem_cache_expire: 0
    
    metadata_mem_cache_size: 128m

    max_task_count: 400

binaryData: {}
