apiVersion: v1
kind: Service
metadata:
  name: prop3d-hsds
  namespace: prop3d
  labels:
    app: prop3d-hsds
spec:
  selector:
    app: prop3d-hsds
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 5101
