apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prop3d-arctic-minio-nfs-pvc
  namespace: prop3d
spec:
  storageClassName: csi-cephfs-sc
  accessModes:
    - ReadWriteMany  #must be the same as PersistentVolume
  resources:
    requests:
      storage: 10Gi
