apiVersion: v1
kind: Service
metadata:
  name: prop3d-arctic-minio-service
  namespace: prop3d
spec:
  selector:
    app: prop3d-arctic-minio
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
